name: Build
on:
  push:
    branches: [main]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: browser-actions/setup-chrome@v1
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build:fingerprint
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: dist
          path: dist/
          retention-days: 7
      - name: Configure AWS Credentials Development
        if: github.event_name == 'pull_request'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::228243989488:role/ci/ci-fingerprint-development-upload
          role-session-name: ci-fingerprint-development-upload
          aws-region: ${{ vars.AWS_REGION }}
      - name: Development Deploy
        if: github.event_name == 'pull_request'
        working-directory: ./dist
        run: |
          aws s3 cp . s3://cam-cdn-fingerprint-script-development-staging-origin/${{github.event.pull_request.head.sha}}/ --recursive --exclude "*" --include="fingerprint.js" --content-type="text/javascript"
      - name: Configure AWS Credentials Staging
        if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::228243989488:role/ci/ci-fingerprint-upload
          role-session-name: ci-fingerprint-upload
          aws-region: ${{ vars.AWS_REGION }}
      - name: Staging Deploy
        if: github.ref == 'refs/heads/main'
        working-directory: ./dist
        run: |
          aws s3 cp . s3://cam-cdn-fingerprint-script-staging-origin/ --recursive --exclude "*" --include="fingerprint.js" --content-type="text/javascript"
          aws cloudfront create-invalidation --distribution-id E108OSBUN9XAH1 --paths "/*"
      - name: Configure AWS Credentials Production
        if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::580831181531:role/ci/ci-fingerprint-upload
          role-session-name: ci-fingerprint-upload
          aws-region: ${{ vars.AWS_REGION }}
      - name: Production Deploy
        if: github.ref == 'refs/heads/main'
        working-directory: ./dist
        run: |
          aws s3 cp . s3://cam-cdn-fingerprint-script-production-origin/ --recursive --exclude "*" --include="fingerprint.js" --content-type="text/javascript"
          aws cloudfront create-invalidation --distribution-id EWARMLVIQ5QN8 --paths "/*"
